# MongoDB Atlas connection
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://examly:root@cluster0.s6v9h74.mongodb.net/expense_tracker?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.database=expense_tracker

server.port=8080
