# MongoDB Atlas connection
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://examly:root@cluster0.s6v9h74.mongodb.net/expense_tracker?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=30000&socketTimeoutMS=30000&maxPoolSize=50}
spring.data.mongodb.database=expense_tracker
spring.data.mongodb.auto-index-creation=true

server.port=8080
